outputDir=build
cacheDir=buildcache
arduinoDir=/Applications/Arduino.app/Contents/Java
arduinoDataDir=/Users/jcoon/Library/Arduino15
arduinoSketchBookDir=/Users/jcoon/Documents/Arduino

mkdir -p $outputDir/
mkdir -p $cacheDir/

# $arduinoDir/arduino-builder -compile -logger=machine -hardware $arduinoDir/hardware -hardware $arduinoDataDir/packages -hardware $arduinoSketchBookDir/hardware -tools $arduinoDir/tools-builder -tools $arduinoDir/hardware/tools/avr -tools $arduinoDataDir/packages -built-in-libraries $arduinoDir/libraries -libraries $arduinoSketchBookDir/libraries -fqbn=esp8266:esp8266:d1_mini:CpuFrequency=160,UploadSpeed=921600,FlashSize=4M3M -ide-version=10612 -build-path $outputDir/ -warnings=none -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.esptool.path=$arduinoDataDir/packages/esp8266/tools/esptool/0.4.9 -prefs=runtime.tools.xtensa-lx106-elf-gcc.path=$arduinoDataDir/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2 -prefs=runtime.tools.mkspiffs.path=$arduinoDataDir/packages/esp8266/tools/mkspiffs/0.1.2 -verbose tree-v2.ino

/Applications/Arduino.app/Contents/Java/arduino-builder -dump-prefs -logger=machine -hardware /Applications/Arduino.app/Contents/Java/hardware -hardware $arduinoDataDir/packages -tools /Applications/Arduino.app/Contents/Java/tools-builder -tools /Applications/Arduino.app/Contents/Java/hardware/tools/avr -tools $arduinoDataDir/packages -built-in-libraries /Applications/Arduino.app/Contents/Java/libraries -libraries $arduinoSketchBookDir/libraries -fqbn=esp8266:esp8266:d1_mini:xtal=160,vt=flash,exception=disabled,eesz=4M1M,ip=lm2f,dbg=Disabled,lvl=None____,wipe=none,baud=921600 -vid-pid=1A86_7523 -ide-version=10809 -build-path $outputDir/ -warnings=none -build-cache $cacheDir/ -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.esptool.path=$arduinoDataDir/packages/esp8266/tools/esptool/2.5.0-3-20ed2b9 -prefs=runtime.tools.esptool-2.5.0-3-20ed2b9.path=$arduinoDataDir/packages/esp8266/tools/esptool/2.5.0-3-20ed2b9 -prefs=runtime.tools.mkspiffs.path=$arduinoDataDir/packages/esp8266/tools/mkspiffs/2.5.0-3-20ed2b9 -prefs=runtime.tools.mkspiffs-2.5.0-3-20ed2b9.path=$arduinoDataDir/packages/esp8266/tools/mkspiffs/2.5.0-3-20ed2b9 -prefs=runtime.tools.xtensa-lx106-elf-gcc.path=$arduinoDataDir/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9 -prefs=runtime.tools.xtensa-lx106-elf-gcc-2.5.0-3-20ed2b9.path=$arduinoDataDir/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9 -verbose esp8266-fastled-webserver.ino

/Applications/Arduino.app/Contents/Java/arduino-builder -compile -logger=machine -hardware /Applications/Arduino.app/Contents/Java/hardware -hardware $arduinoDataDir/packages -tools /Applications/Arduino.app/Contents/Java/tools-builder -tools /Applications/Arduino.app/Contents/Java/hardware/tools/avr -tools $arduinoDataDir/packages -built-in-libraries /Applications/Arduino.app/Contents/Java/libraries -libraries $arduinoSketchBookDir/libraries -fqbn=esp8266:esp8266:d1_mini:xtal=160,vt=flash,exception=disabled,eesz=4M1M,ip=lm2f,dbg=Disabled,lvl=None____,wipe=none,baud=921600 -vid-pid=1A86_7523 -ide-version=10809 -build-path $outputDir/ -warnings=none -build-cache $cacheDir/ -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.esptool.path=$arduinoDataDir/packages/esp8266/tools/esptool/2.5.0-3-20ed2b9 -prefs=runtime.tools.esptool-2.5.0-3-20ed2b9.path=$arduinoDataDir/packages/esp8266/tools/esptool/2.5.0-3-20ed2b9 -prefs=runtime.tools.mkspiffs.path=$arduinoDataDir/packages/esp8266/tools/mkspiffs/2.5.0-3-20ed2b9 -prefs=runtime.tools.mkspiffs-2.5.0-3-20ed2b9.path=$arduinoDataDir/packages/esp8266/tools/mkspiffs/2.5.0-3-20ed2b9 -prefs=runtime.tools.xtensa-lx106-elf-gcc.path=$arduinoDataDir/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9 -prefs=runtime.tools.xtensa-lx106-elf-gcc-2.5.0-3-20ed2b9.path=$arduinoDataDir/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9 -verbose esp8266-fastled-webserver.ino